### PR TITLE
Bug 2073525: Update vpc-node-label-updater to v4.1.2

### PR DESCRIPTION
**Pull request by dobsonj**
https://bugzilla.redhat.com/show_bug.cgi?id=2073522
https://github.com/IBM/vpc-node-label-updater/compare/v4.1.2...dobsonj:rebase-v4.1.2
/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
/hold
for QE approval

**Comment by chao007** [comment]
lgtm

**Pull request merged**
